version: '2'

networks:
  net:
    driver: bridge

services:
  mongodb:
    image: 'mongo:4.2.6'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sa
      - MONGO_INITDB_ROOT_PASSWORD=1q2w3e4r
    ports:
      - 27017:27017
    networks:
      - net

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - net